New message functions
USERSATOSHI/aoi.js pull request #2
Opened 2024-11-07 20:32 UTC by supremesupreme

## Description
New list of message based functions + tests

Fixes # (issue number / __remove this line__ if no issue is to be referenced)

## Type of change

Please check options that describe your Pull Request:

- [ ] Bug fix (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

- [x] My code follows the style guidelines of this project
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-08 03:08 UTC, USERSATOSHI requested changes

2024-11-08 03:08 UTC, USERSATOSHI commented on lib/aoi.js/src/core/parsers/string.ts
> +	while (i <= text?.length) {
text needs to be defined for this function 

so having optional chaining here is not desirable

2024-11-08 03:08 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageexists.ts
> +			messageid == undefined &&
do !messageId

2024-11-08 03:08 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageexists.ts
> +		}
this could be a !channelId first to handle undefined case then do parseData for both at same place

2024-11-08 03:08 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageexists.ts
> +		);
channelId can be undefined 

also use camelCase for variable Names so channelId and not channelid same for rest

2024-11-08 03:08 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageflags.ts
> +		}
follow error early return pattern as this parseChannelId  is useless

2024-11-08 03:08 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagepublish.ts
> +		}
follow error early pattern

2024-11-08 03:08 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageslice.ts
> +			[parseString(from), parseString(to)],
use parsedFrom and parsedTo

2024-11-08 03:08 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagetype.ts
> +		}
same for this

2024-11-08 03:08 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageurl.ts
> +		}
same for this

2024-11-08 03:08 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagewebhookid.ts
> +
same for this

2024-11-08 03:33 UTC, supremesupreme commented on lib/aoi.js/src/functions/discord/message/$messageflags.ts
> +		}
Going to assume this means handle undefined first

2024-11-08 03:34 UTC, supremesupreme commented on lib/aoi.js/src/functions/discord/message/$messagepublish.ts
> +		}
Same for undefined issue aswell

2024-11-08 03:47 UTC, USERSATOSHI requested changes

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageexists.ts
> +		let parsedChannelId = thisArg.parseData(messageId, ReturnType.Number);
this should be ReturnType.String

as ids are required as string

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageexists.ts
> +			!thisArg.isCorrectType(parsedMessageId, ReturnType.Number) &&
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageexists.ts
> +			!thisArg.isCorrectType(parsedChannelId, ReturnType.Number) &&
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageflags.ts
> +		let parsedChannelId = thisArg.parseData(channelId, ReturnType.Number);
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageflags.ts
> +		let parsedMessageId = thisArg.parseData(messageId, ReturnType.Number);
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageflags.ts
> +		if (!thisArg.isCorrectType(parsedMessageId, ReturnType.Number) && !thisArg.canSuppressAtComp(data, currentScope)) {
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagepublish.ts
> +			!thisArg.isCorrectType(parsedChannelId, ReturnType.Number) &&
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagepublish.ts
> +			!thisArg.isCorrectType(parsedMessageId, ReturnType.Number) &&
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagetype.ts
> +		if (!thisArg.isCorrectType(parsedChannelId, ReturnType.Number) && !thisArg.canSuppressAtComp(data, currentScope)) {
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagetype.ts
> +		if (!thisArg.isCorrectType(parsedMessageId, ReturnType.Number) && !thisArg.canSuppressAtComp(data, currentScope)) {
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageurl.ts
> +		if (!thisArg.isCorrectType(parsedChannelId, ReturnType.Number) && !thisArg.canSuppressAtComp(data, currentScope)) {
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageurl.ts
> +		if (!thisArg.isCorrectType(parsedMessageId, ReturnType.Number) && !thisArg.canSuppressAtComp(data, currentScope)) {
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagewebhookid.ts
> +		if (!thisArg.isCorrectType(parsedChannelId, ReturnType.Number) && !thisArg.canSuppressAtComp(data, currentScope)) {
ReturnType.String

2024-11-08 03:47 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagewebhookid.ts
> +		if (!thisArg.isCorrectType(parsedMessageId, ReturnType.Number) && !thisArg.canSuppressAtComp(data, currentScope)) {
ReturnType.String

2024-11-08 21:15 UTC, USERSATOSHI requested changes

2024-11-08 21:15 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageexists.ts
> +				!!discordData.client.channels.cache.get('$0' || discordData.channel.id)?.messages.fetch('$1'),
remove the || part as the default is set to that

2024-11-08 21:15 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageflags.ts
> +				discordData.client.channels.cache.get('$0' || discordData.channel.id)?.messages.fetch('$1')?.flags.toArray().join('$2') ?? '',
same here

2024-11-08 21:15 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagepublish.ts
> +				(await discordData.client.channels.cache.get('$0' || discordData.channel.id)?.messages.fetch('$1'))?.crosspost() ?? '',
same here

2024-11-08 21:15 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagetype.ts
> +			  (await discordData.client.channels.cache.get('$0' || discordData.channel.id)?.messages.fetch('$1'))?.type ?? '',
same here

2024-11-08 21:15 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messageurl.ts
> +			  (await discordData.client.channels.cache.get('$0' || discordData.channel.id)?.messages.fetch('$1'))?.url ?? '',
same here

2024-11-08 21:15 UTC, USERSATOSHI commented on lib/aoi.js/src/functions/discord/message/$messagewebhookid.ts
> +			  (await discordData.client.channels.cache.get('$0' || discordData.channel.id)?.messages.fetch('$1'))?.webhookId,
same here

2024-11-12 14:52 UTC, USERSATOSHI approved these changes

2024-11-12 14:53 UTC, merged